on:
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - run: sudo apt install python3 ninja-build cmake ccache xdelta3 clang libssl-dev pkg-config
      - run: pip install capstone colorama cxxfilt pyelftools ansiwrap watchdog python-Levenshtein toml
      - run: python3 tools/setup.py
      - run: cmake --build build
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            build/
