on:
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - run: sudo apt update
      - run: sudo apt install python3 ninja-build cmake xdelta3 libssl-dev pkg-config
      - run: pip install capstone colorama cxxfilt pyelftools ansiwrap watchdog python-Levenshtein toml
#       - name: Install LLVM and Clang
#         uses: KyleMayes/install-llvm-action@v1
#         with:
#           version: '16.0.4'
#           ubuntu-version: '22.04'
#           env: true
      - env:
          CC: clang
          CXX: clang++
        run: > 
          cmake -GNinja
          -DCMAKE_BUILD_TYPE=RelWithDebInfo 
          -DCMAKE_TOOLCHAIN_FILE=toolchain/ToolchainNX64.cmake 
          -B build/
      - run: cmake --build build
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            build/**
